name: Something

on:
  workflow_run:
    workflows: [Build]
    types: [completed]

jobs:
  
  is-it:
    runs-on: ubuntu-latest
    name: Is it running ğŸ‡
    steps:
    - uses: actions/checkout@v3

    - name: Use it
      run: echo "ceva sa vad daca merge pe bune ca nu inteleg"